### ISSUE TITLE
Unable to find boxen.js module

### ISSUE THREAD

**Issue by jasonwilczak** [ritz078/rollup-plugin-filesize#82]
I followed a simple setup based on the readme, but I get this when attempting to rollup while using the filesize plugin.

`Error: Cannot find module 'C:/git/my-widget-pkg/node_modules/rollup-plugin-filesize/dist/reporters/boxen.js'`

Full Error Output
````
> rollup -c

babelHelpers: 'bundled' option was used by default. It is recommended to configure this option explicitly, read more here: https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers

src/main.js → bin/component.js...
[!] (plugin filesize) Error: Cannot find module 'C:/git/my-widget-pkg/node_modules/rollup-plugin-filesize/dist/reporters/boxen.js'
Error: Cannot find module 'C:/git/my-widget-pkg/node_modules/rollup-plugin-filesize/dist/reporters/boxen.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at C:\git\my-widget-pkg\node_modules\rollup-plugin-filesize\src\index.js:142:12
    at new Promise (<anonymous>)
    at map (C:\git\my-widget-pkg\node_modules\rollup-plugin-filesize\src\index.js:142:12)
    at Array.map (<anonymous>)
    at getLoggingData (C:\git\my-widget-pkg\node_modules\rollup-plugin-filesize\src\index.js:138:15)
    at Promise.all.Object.keys.map.filter.map.currentBundle (C:\git\my-widget-pkg\node_modules\rollup-plugin-filesize\src\index.js:172:14)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-widget@0.0.1 build: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-widget@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2020-06-10T12_42_34_874Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-widget@0.0.1 test:manual: `npm run build && cd testsManual/react && npm start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-widget@0.0.1 test:manual script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2020-06-10T12_42_34_951Z-debug.log
````

Here is my rollup.config.js

````
import babel from '@rollup/plugin-babel';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import postcss from 'rollup-plugin-postcss';
import filesize from 'rollup-plugin-filesize';
import autoprefixer from 'autoprefixer';
import localResolve from 'rollup-plugin-local-resolve';

import pkg from './package.json';

const INPUT_FILE_PATH = 'src/main.js';
const OUTPUT_NAME = 'MyWidget';

const GLOBALS = {
  react: 'React',
  'react-dom': 'ReactDOM',
};

const PLUGINS = [	
	filesize(),
  postcss({
    extract: true,
    plugins: [
      autoprefixer,
    ],
  }),
  babel({
    exclude: 'node_modules/**',
  }),
  localResolve(),
  resolve({
    browser: true,
  }),
  commonjs()
];

const EXTERNAL = [
  'react',
  'react-dom',
];

const OUTPUT_DATA = [
  {
    file: pkg.browser,
    format: 'umd',
  },
  {
    file: pkg.main,
    format: 'cjs',
  },
  {
    file: pkg.module,
    format: 'es',
  },
];

const config = OUTPUT_DATA.map(({ file, format }) => ({
  input: INPUT_FILE_PATH,
  output: {
    file,
    format,
    name: OUTPUT_NAME,
    globals: GLOBALS,
  },
  external: EXTERNAL,
  plugins: PLUGINS,
}));

export default config;
````

**Comment by ritz078** [comment]
@brettz9 any idea about this ?

**Comment by brettz9** [comment]
Firstly is "C:/git/my-widget-pkg/node_modules/rollup-plugin-filesize/dist/reporters/boxen.js" present on the file system? If it is present, I'm guessing it is a Windows path issue.

**Comment by BlueGhostGH** [comment]
I am encountering the same issue. I've made sure that the file is actually present. And if it is a Windows path issue, what could I do about it?

**Comment by brettz9** [comment]
I don't have a Windows machine to debug on.

In `/dist/index.js`, can you try changing:

```js
p = new Promise(function (resolve) { resolve(_interopNamespace(require(thisDirectory + "/reporters/boxen.js"))); });
```

...to:

```js
p = new Promise(function (resolve) { resolve(_interopNamespace(require(path.join(thisDirectory, "reporters", "boxen.js")))); });
```

**Comment by brettz9** [comment]
or maybe:

```js
p = new Promise(function (resolve) { resolve(_interopNamespace(require(path.normalize(path.join(thisDirectory, "reporters", "boxen.js"))))); });
```

**Comment by charlex** [comment]
Is it possible that spaces in folder names are triggering this error?

**Comment by morteza-fsh** [comment]
Same as @charlex said, space in the path causes the error, and seems the fix is not merged yet.

**Comment by brettz9** [comment]
An exact error might still be helpful.

**Comment by morteza-fsh** [comment]
This is the error message:
`[!] (plugin filesize) Error: Cannot find module '/Users/mrt/Projects/avt/Sample%20Project/node_modules/rollup-plugin-filesize/dist/reporters/boxen.js'
Require stack:
- /Users/mrt/Projects/avt/Sample Project/node_modules/rollup-plugin-filesize/dist/index.js
- /Users/mrt/Projects/avt/Sample Project/apps/player/rollup.config.js
- /Users/mrt/Projects/avt/Sample Project/node_modules/rollup/dist/shared/loadConfigFile.js
- /Users/mrt/Projects/avt/Sample Project/node_modules/rollup/dist/bin/rollup`

As you can see boxen.js module doesn't load as the path contains a space character (%20)
